In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("pp2.csv")

In [3]:
data

,표측1,2019,2019.1,2019.2,2019.3,2019.4,2019.5,2019.6,2019.7,2019.8,...,2011.9,2011.10,2011.11,2011.12,2011.13,2011.14,2011.15,2011.16,2011.17,2011.18
0,표측1,1.사례수,10.유흥/놀이시설,11.경제적인 여행비용,12.잘갖춰진휴양시설,13.기후/뚜렷한 사계절,14.가까운 거리,15.휴양/휴식,16.안전,"16.친구, 친지 방문",...,"17.드라마, 영화촬영지 방문, 한류 스타 팬미팅",18.여행 가능한 여가시간,2.쇼핑,3.음식/미식탐방,4.자연풍경감상,5.역사/문화유적,6.패션/유행 등 세련된 문화,7.휴가 시간,8.K-POP/한류스타 팬미팅 등을 경험하고 싶어서,9.자국과의 이동거리
1,1.전체,NaN,6.3,6.2,NaN,NaN,NaN,NaN,NaN,NaN,...,8.2,NaN,66.6,44.2,23.9,19.1,14.5,NaN,NaN,NaN
2,10.9월,NaN,4.6,5.5,NaN,NaN,NaN,NaN,NaN,NaN,...,11.9,NaN,64.8,43,21.5,16.4,15,NaN,NaN,NaN
3,11.10월,NaN,4.9,6.1,NaN,NaN,NaN,NaN,NaN,NaN,...,6.2,NaN,61.4,37.2,30.5,31.2,12.5,NaN,NaN,NaN
4,12.11월,NaN,3.9,5.6,NaN,NaN,NaN,NaN,NaN,NaN,...,8.1,NaN,66.1,46.4,22.9,18.7,17.6,NaN,NaN,NaN
5,13.12월,NaN,5.8,4,NaN,NaN,NaN,NaN,NaN,NaN,...,4.3,NaN,69.1,46.5,28.5,20.9,13.3,NaN,NaN,NaN
6,2.1월,NaN,5.2,6.8,NaN,NaN,NaN,NaN,NaN,NaN,...,9.4,NaN,58.8,47.7,19.8,16.5,10.5,NaN,NaN,NaN
7,3.2월,NaN,4.7,6.4,NaN,NaN,NaN,NaN,NaN,NaN,...,12.4,NaN,73.1,49.9,19.8,13.1,13.8,NaN,NaN,NaN
8,4.3월,NaN,6.2,6.7,NaN,NaN,NaN,NaN,NaN,NaN,...,7,NaN,69.7,44.6,24.5,16.6,10.6,NaN,NaN,NaN
9,5.4월,NaN,8.3,6.5,NaN,NaN,NaN,NaN,NaN,NaN,...,7.4,NaN,70,43.1,27.3,18.7,11.9,NaN,NaN,NaN
10,6.5월,NaN,6.7,6.2,NaN,NaN,NaN,NaN,NaN,NaN,...,8.9,NaN,70.9,42.8,21.8,13.9,12.8,NaN,NaN,NaN
11,7.6월,NaN,9.8,6.6,NaN,NaN,NaN,NaN,NaN,NaN,...,9,NaN,69.4,44.2,25,15.6,15.5,NaN,NaN,NaN
12,8.7월,NaN,8.5,6.2,NaN,NaN,NaN,NaN,NaN,NaN,...,10.1,NaN,64.2,42.7,20.2,16.2,17.7,NaN,NaN,NaN
13,9.8월,NaN,6.5,8.3,NaN,NaN,NaN,NaN,NaN,NaN,...,6.5,NaN,63.8,46.1,21.7,23.6,19.2,NaN,NaN,NaN

In [4]:
data.iloc[:,:96]

,표측1,2019,2019.1,2019.2,2019.3,2019.4,2019.5,2019.6,2019.7,2019.8,...,2015.9,2015.10,2015.11,2015.12,2015.13,2015.14,2015.15,2015.16,2015.17,2015.18
0,표측1,1.사례수,10.유흥/놀이시설,11.경제적인 여행비용,12.잘갖춰진휴양시설,13.기후/뚜렷한 사계절,14.가까운 거리,15.휴양/휴식,16.안전,"16.친구, 친지 방문",...,"17.드라마, 영화촬영지 방문, 한류 스타 팬미팅",18.여행 가능한 여가시간,2.쇼핑,3.음식/미식탐방,4.자연풍경감상,5.역사/문화유적,6.패션/유행 등 세련된 문화,7.휴가 시간,8.K-POP/한류스타 팬미팅 등을 경험하고 싶어서,9.자국과의 이동거리
1,1.전체,NaN,6.3,6.2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.5,67.8,42.8,44.8,27.6,23.6,NaN,NaN,NaN
2,10.9월,NaN,4.6,5.5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,13.1,61.6,45,42.5,30.8,25.2,NaN,NaN,NaN
3,11.10월,NaN,4.9,6.1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.3,67.3,45.7,43.3,25.5,26.5,NaN,NaN,NaN
4,12.11월,NaN,3.9,5.6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,11.5,71.2,45.2,45.2,27.2,22.8,NaN,NaN,NaN
5,13.12월,NaN,5.8,4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,13.3,68.1,44.7,38.4,20.2,26.8,NaN,NaN,NaN
6,2.1월,NaN,5.2,6.8,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9.8,68.6,39.5,50.3,27.2,18.6,NaN,NaN,NaN
7,3.2월,NaN,4.7,6.4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.7,65,39.2,44.6,25,18.6,NaN,NaN,NaN
8,4.3월,NaN,6.2,6.7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6.7,74.8,44.7,48.7,34.7,18.8,NaN,NaN,NaN
9,5.4월,NaN,8.3,6.5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8,71.1,38.6,49.7,32.2,24.8,NaN,NaN,NaN
10,6.5월,NaN,6.7,6.2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10.1,71.6,43.7,44.1,24.6,29.8,NaN,NaN,NaN
11,7.6월,NaN,9.8,6.6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8.4,64.3,48.2,41.9,27.7,23.6,NaN,NaN,NaN
12,8.7월,NaN,8.5,6.2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,14.8,58.3,31.9,46.1,24.7,21.8,NaN,NaN,NaN
13,9.8월,NaN,6.5,8.3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,12.1,59.8,43.6,39.9,27.7,22.9,NaN,NaN,NaN

In [5]:
data2 = data.iloc[:,:96].dropna(axis=1)
data2

,표측1,2019.1,2019.2,2019.11,2019.12,2019.13,2019.14,2019.15,2019.16,2019.17,...,2015.1,2015.2,2015.4,2015.5,2015.10,2015.11,2015.12,2015.13,2015.14,2015.15
0,표측1,10.유흥/놀이시설,11.경제적인 여행비용,2.쇼핑,3.음식/미식탐방,4.자연풍경감상,5.역사/문화유적,6.패션/유행 등 세련된 문화,7.휴가 시간,8.K-POP/한류스타 팬미팅 등을 경험하고 싶어서,...,10.유흥/놀이시설,11.경제적인 여행비용,13.기후/뚜렷한 사계절,14.가까운 거리,18.여행 가능한 여가시간,2.쇼핑,3.음식/미식탐방,4.자연풍경감상,5.역사/문화유적,6.패션/유행 등 세련된 문화
1,1.전체,6.3,6.2,66.2,61.3,36.3,23.6,19.4,19,12.7,...,10,9.3,8.4,8.9,10.5,67.8,42.8,44.8,27.6,23.6
2,10.9월,4.6,5.5,65.1,59.9,36.2,24.9,23.5,21.4,11.1,...,8.8,9.2,7.8,14.1,13.1,61.6,45,42.5,30.8,25.2
3,11.10월,4.9,6.1,60.6,57.7,42.1,25.3,18.1,17.2,18.9,...,7.6,10.7,8.9,7.6,10.3,67.3,45.7,43.3,25.5,26.5
4,12.11월,3.9,5.6,70.4,57.4,37,23.6,21.2,17.4,10,...,7.4,10.3,9.9,7.9,11.5,71.2,45.2,45.2,27.2,22.8
5,13.12월,5.8,4,68.4,62,38.4,22,21.7,20.6,11.6,...,7.6,9.7,13.9,9.4,13.3,68.1,44.7,38.4,20.2,26.8
6,2.1월,5.2,6.8,66.5,64.9,33.9,20.6,15.7,16.2,20.3,...,12.1,14.7,5.6,5.4,9.8,68.6,39.5,50.3,27.2,18.6
7,3.2월,4.7,6.4,69.9,65.9,35.9,22.5,19.8,15.4,10,...,14.4,10.5,7.2,7.3,10.7,65,39.2,44.6,25,18.6
8,4.3월,6.2,6.7,72,62.8,34.5,20,20.2,17.6,13.8,...,9,7.1,7.9,6,6.7,74.8,44.7,48.7,34.7,18.8
9,5.4월,8.3,6.5,63.8,61.8,39.9,27,16.4,20.6,9.7,...,11.6,9.2,8.5,7.4,8,71.1,38.6,49.7,32.2,24.8
10,6.5월,6.7,6.2,66,60.8,36.5,25,16.5,20.3,11.3,...,9.8,6.9,6.7,9.8,10.1,71.6,43.7,44.1,24.6,29.8
11,7.6월,9.8,6.6,66.2,64.3,34.1,24.4,18.4,18.7,12.6,...,11.4,4.9,5.6,5.8,8.4,64.3,48.2,41.9,27.7,23.6
12,8.7월,8.5,6.2,65,58.5,32,21.4,21.4,21.1,15,...,8.3,7.9,9.6,16.2,14.8,58.3,31.9,46.1,24.7,21.8
13,9.8월,6.5,8.3,62,61.6,33,24.5,20.4,20,9,...,12.7,8.9,9.2,13.4,12.1,59.8,43.6,39.9,27.7,22.9

In [6]:
data2.loc[1]

표측1            1.전체
2019.1          6.3
2019.2          6.2
2019.11        66.2
2019.12        61.3
2019.13        36.3
2019.14        23.6
2019.15        19.4
2019.16          19
2019.17        12.7
2019.18         8.7
2018.2          6.6
2018.8         20.4
2018.11        63.8
2018.12        57.9
2018.13        36.2
2018.14        14.8
2018.15        13.1
2018.16        12.4
2018.17         9.3
2018.18         7.4
2017       8,983.00
2017.1          9.3
2017.2         11.3
2017.5         12.3
2017.10        10.7
2017.11        62.2
2017.12        52.8
2017.13        36.4
2017.14        19.8
2017.15        25.4
2017.17        10.7
2016       8,827.00
2016.1          8.5
2016.2         10.1
2016.3          9.8
2016.5         12.2
2016.10         9.6
2016.11        67.3
2016.12        44.5
2016.13        43.2
2016.14        25.6
2016.15        25.4
2015       8,817.00
2015.1           10
2015.2          9.3
2015.4          8.4
2015.5          8.9
2015.10        10.5
2015.11        67.8
2015.12        42.8
2015.13        44.8
2015.14        27.6
2015.15        23.6
Name: 1, dtype: object