In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import pyplot
from scipy import stats

In [2]:
df2 = pd.read_csv("한국_방문_선택_시_고려요인.csv", encoding='cp949')
df2

,통계분류(1),통계분류(2),2021,2021.1,2021.2,2021.3,2021.4,2021.5,2021.6,2021.7,2021.8,2021.9,2021.10,2021.11,2021.12,2021.13
0,통계분류(1),통계분류(2),사례수,음식/미식탐방,쇼핑,자연 풍경 감상,패션 유행 등 세련된 현대 문화 체험,역사/문화유적/전통문화 체험,유흥/놀이 시설 체험,치료 및 미용 서비스 체험,여행 가능한 여가시간,K-POP/한류스타 관련 공연팬미팅촬영지 등 체험,레저 및 스포츠 활동,자국과의 이동거리,경제적인 여행비용,기타
1,전체,소계,1398,20.1,12.7,11.4,4,3.9,1.5,1.4,1.4,1.1,0.7,0.6,0.4,41
2,월별,1월,117,18.8,16.2,11.1,10.3,1.7,0,0,3.4,0,0.9,0,0,37.6
3,월별,2월,90,22.2,15.6,12.2,3.3,4.4,2.2,2.2,2.2,0,0,1.1,0,34.4
4,월별,3월,54,20.4,14.8,13,5.6,5.6,0,1.9,0,0,1.9,0,0,37
5,월별,4월,86,19.8,12.8,17.4,5.8,0,1.2,3.5,0,0,1.2,0,0,38.4
6,월별,5월,102,17.6,8.8,14.7,13.7,4.9,2,2,0,1,0,1,0,34.3
7,월별,6월,64,20.3,7.8,10.9,6.3,1.6,0,4.7,1.6,0,0,0,0,46.9
8,월별,7월,65,18.5,13.8,13.8,0,3.1,0,3.1,0,1.5,0,1.5,0,44.6
9,월별,8월,116,10.3,10.3,6.9,0,5.2,1.7,0,0,0,0.9,0,0,64.7
10,월별,9월,157,13.4,13.4,8.3,1.9,3.2,1.9,1.9,1.3,0,0,0.6,0.6,53.5
11,월별,10월,156,14.7,9.6,10.9,2.6,5.1,1.9,0,1.3,0,0.6,0.6,1.3,51.3
12,월별,11월,236,25,14.8,10.2,1.7,5.1,1.3,1.3,2.1,3,0.8,0.8,0.8,33.1
13,월별,12월,155,34.2,12.3,12.9,2.6,3.9,3.2,0,1.9,3.9,1.9,1.3,0,21.9
14,분기,1분기,261,20.3,15.7,11.9,6.9,3.4,0.8,1.1,2.3,0,0.8,0.4,0,36.4
15,분기,2분기,252,19,9.9,14.7,9.1,2.4,1.2,3.2,0.4,0.4,0.4,0.4,0,38.9
16,분기,3분기,338,13.3,12.4,8.9,0.9,3.8,1.5,1.5,0.6,0.3,0.3,0.6,0.3,55.6
17,분기,4분기,547,24.7,12.6,11.2,2.2,4.8,2,0.5,1.8,2.4,1.1,0.9,0.7,35.1
18,국가,일본,26,30.8,7.7,3.8,3.8,0,0,0,0,0,0,3.8,0,50
19,국가,중국,297,19.2,22.6,16.8,11.8,1.7,0,1.3,0,0,0.3,0.3,0,25.9
20,국가,홍콩,1,0,100,0,0,0,0,0,0,0,0,0,0,0
21,국가,싱가포르,181,44.2,18.2,16.6,1.1,3.9,3.3,0.6,1.1,3.3,2.8,1.1,0,3.9
22,국가,대만,12,33.3,16.7,0,8.3,16.7,0,8.3,0,0,0,0,0,16.7
23,국가,태국,23,21.7,39.1,21.7,0,4.3,0,4.3,4.3,0,0,0,0,4.3
24,국가,말레이시아,5,40,40,20,0,0,0,0,0,0,0,0,0,0
25,국가,호주,4,25,25,25,0,0,0,0,0,0,0,0,0,25
26,국가,미국,449,11.8,4.5,7.3,0.9,2.7,1.6,1.1,2,0.9,0.4,0.7,0.2,65.9
27,국가,캐나다,23,13,4.3,0,0,4.3,0,4.3,4.3,0,0,0,0,69.6
28,국가,영국,57,14,8.8,14,1.8,7,5.3,0,0,0,1.8,0,5.3,42.1
29,국가,독일,28,21.4,3.6,10.7,0,10.7,0,0,0,0,3.6,0,0,50
30,국가,프랑스,71,16.9,4.2,4.2,2.8,8.5,2.8,0,1.4,0,0,0,0,59.2
31,국가,러시아,26,26.9,15.4,7.7,3.8,3.8,0,11.5,0,3.8,0,0,0,26.9
32,국가,중동,23,13,13,8.7,4.3,0,0,0,4.3,0,0,0,0,56.5
33,국가,인도,3,33.3,0,33.3,0,0,0,0,0,0,0,0,0,33.3
34,국가,필리핀,7,28.6,14.3,28.6,14.3,0,0,0,0,0,0,0,0,14.3
35,국가,인도네시아,7,28.6,28.6,0,0,0,0,0,0,0,0,0,0,42.9
36,국가,베트남,9,0,22.2,11.1,11.1,0,0,11.1,0,0,0,0,0,44.4
37,국가,몽골,10,0,30,20,10,0,10,10,0,0,0,10,0,10
38,국가,기타,136,19.9,11,10.3,3.7,8.8,1.5,0.7,2.9,2.9,0,0.7,0.7,36.8
39,성별,남성,576,23.3,9.4,10.2,3.6,4.2,1.6,1,1.9,0.5,1,1,0.3,41.8
40,성별,여성,822,17.9,15,12.2,4.3,3.6,1.5,1.6,1,1.5,0.5,0.4,0.4,40.4
41,연령,15-20 세,63,28.6,9.5,15.9,4.8,6.3,4.8,0,1.6,4.8,0,1.6,0,22.2
42,연령,21-30 세,389,22.9,11.8,12.1,4.6,4.9,2.3,1,1.3,1.8,0.3,0.8,0.3,36
43,연령,31-40 세,405,21,16.8,8.9,6.2,4,1.2,2,2.5,1,1,0.2,0.5,34.8
44,연령,41-50 세,201,19.4,13.4,11.9,4,0.5,0.5,2,0.5,0.5,1,1,0.5,44.8
45,연령,51-60 세,222,13.1,10.4,12.2,0.5,5,1.4,0.5,0.5,0,0.9,0.9,0,55
46,연령,61 세이상,118,17.8,5.9,12.7,0.8,2.5,0,1.7,0.8,0,0.8,0,0.8,55.9
47,방한목적,여가/위락/휴식,316,38.6,17.7,14.9,1.9,7.6,3.5,3.5,2.2,4.4,1.6,1.3,0,2.8
48,방한목적,친구/친지방문,1082,14.7,11.2,10.4,4.6,2.8,0.9,0.7,1.1,0.1,0.5,0.5,0.5,52.1
49,입국과정,자가격리포함,787,17.7,13.3,11.2,5,3.4,1.4,1.8,1.7,0.8,0.6,0.8,0.1,42.3
50,입국과정,자가격리미포함,611,23.2,11.8,11.6,2.8,4.4,1.6,0.8,1,1.5,0.8,0.5,0.7,39.3
51,방한횟수,1회,370,18.1,14.1,11.9,2.4,8.1,1.1,0.8,1.6,2.2,0.5,0.8,0,38.4
52,방한횟수,2회,241,24.1,8.7,9.5,3.3,2.5,1.2,2.1,1.2,1.2,0.8,1.7,0.8,42.7
53,방한횟수,3회,181,21,8.3,11.6,3.9,2.8,3.3,1.7,0.6,0.6,0.6,0.6,0,45.3
54,방한횟수,4회 이상,606,19.5,14.7,11.7,5.3,2.1,1.3,1.3,1.5,0.5,0.8,0.2,0.5,40.6

In [3]:
df2.rename(columns = {"2021":"사례수","2021.1":"음식/미식탐방", "2021.2":"쇼핑", "2021.3":"자연 풍경 감상", "2021.4":"패션 유행 등 세련된 현대 문화 체험",
                       "2021.5":"역사/문화유적/전통문화 체험", "2021.6":"유흥/놀이 시설 체험", "2021.7":"치료 및 미용 서비스 체험", 
                       "2021.8":"여행 가능한 여가시간", "2021.9":"K-POP/한류스타 관련 공연팬미팅촬영지 등 체험", 
                       "2021.10":"레저 및 스포츠 활동", "2021.11":"자국과의 이동거리", "2021.12":"경제적인 여행비용","2021.13":"기타"}, inplace=True)
df2

,통계분류(1),통계분류(2),사례수,음식/미식탐방,쇼핑,자연 풍경 감상,패션 유행 등 세련된 현대 문화 체험,역사/문화유적/전통문화 체험,유흥/놀이 시설 체험,치료 및 미용 서비스 체험,여행 가능한 여가시간,K-POP/한류스타 관련 공연팬미팅촬영지 등 체험,레저 및 스포츠 활동,자국과의 이동거리,경제적인 여행비용,기타
0,통계분류(1),통계분류(2),사례수,음식/미식탐방,쇼핑,자연 풍경 감상,패션 유행 등 세련된 현대 문화 체험,역사/문화유적/전통문화 체험,유흥/놀이 시설 체험,치료 및 미용 서비스 체험,여행 가능한 여가시간,K-POP/한류스타 관련 공연팬미팅촬영지 등 체험,레저 및 스포츠 활동,자국과의 이동거리,경제적인 여행비용,기타
1,전체,소계,1398,20.1,12.7,11.4,4,3.9,1.5,1.4,1.4,1.1,0.7,0.6,0.4,41
2,월별,1월,117,18.8,16.2,11.1,10.3,1.7,0,0,3.4,0,0.9,0,0,37.6
3,월별,2월,90,22.2,15.6,12.2,3.3,4.4,2.2,2.2,2.2,0,0,1.1,0,34.4
4,월별,3월,54,20.4,14.8,13,5.6,5.6,0,1.9,0,0,1.9,0,0,37
5,월별,4월,86,19.8,12.8,17.4,5.8,0,1.2,3.5,0,0,1.2,0,0,38.4
6,월별,5월,102,17.6,8.8,14.7,13.7,4.9,2,2,0,1,0,1,0,34.3
7,월별,6월,64,20.3,7.8,10.9,6.3,1.6,0,4.7,1.6,0,0,0,0,46.9
8,월별,7월,65,18.5,13.8,13.8,0,3.1,0,3.1,0,1.5,0,1.5,0,44.6
9,월별,8월,116,10.3,10.3,6.9,0,5.2,1.7,0,0,0,0.9,0,0,64.7
10,월별,9월,157,13.4,13.4,8.3,1.9,3.2,1.9,1.9,1.3,0,0,0.6,0.6,53.5
11,월별,10월,156,14.7,9.6,10.9,2.6,5.1,1.9,0,1.3,0,0.6,0.6,1.3,51.3
12,월별,11월,236,25,14.8,10.2,1.7,5.1,1.3,1.3,2.1,3,0.8,0.8,0.8,33.1
13,월별,12월,155,34.2,12.3,12.9,2.6,3.9,3.2,0,1.9,3.9,1.9,1.3,0,21.9
14,분기,1분기,261,20.3,15.7,11.9,6.9,3.4,0.8,1.1,2.3,0,0.8,0.4,0,36.4
15,분기,2분기,252,19,9.9,14.7,9.1,2.4,1.2,3.2,0.4,0.4,0.4,0.4,0,38.9
16,분기,3분기,338,13.3,12.4,8.9,0.9,3.8,1.5,1.5,0.6,0.3,0.3,0.6,0.3,55.6
17,분기,4분기,547,24.7,12.6,11.2,2.2,4.8,2,0.5,1.8,2.4,1.1,0.9,0.7,35.1
18,국가,일본,26,30.8,7.7,3.8,3.8,0,0,0,0,0,0,3.8,0,50
19,국가,중국,297,19.2,22.6,16.8,11.8,1.7,0,1.3,0,0,0.3,0.3,0,25.9
20,국가,홍콩,1,0,100,0,0,0,0,0,0,0,0,0,0,0
21,국가,싱가포르,181,44.2,18.2,16.6,1.1,3.9,3.3,0.6,1.1,3.3,2.8,1.1,0,3.9
22,국가,대만,12,33.3,16.7,0,8.3,16.7,0,8.3,0,0,0,0,0,16.7
23,국가,태국,23,21.7,39.1,21.7,0,4.3,0,4.3,4.3,0,0,0,0,4.3
24,국가,말레이시아,5,40,40,20,0,0,0,0,0,0,0,0,0,0
25,국가,호주,4,25,25,25,0,0,0,0,0,0,0,0,0,25
26,국가,미국,449,11.8,4.5,7.3,0.9,2.7,1.6,1.1,2,0.9,0.4,0.7,0.2,65.9
27,국가,캐나다,23,13,4.3,0,0,4.3,0,4.3,4.3,0,0,0,0,69.6
28,국가,영국,57,14,8.8,14,1.8,7,5.3,0,0,0,1.8,0,5.3,42.1
29,국가,독일,28,21.4,3.6,10.7,0,10.7,0,0,0,0,3.6,0,0,50
30,국가,프랑스,71,16.9,4.2,4.2,2.8,8.5,2.8,0,1.4,0,0,0,0,59.2
31,국가,러시아,26,26.9,15.4,7.7,3.8,3.8,0,11.5,0,3.8,0,0,0,26.9
32,국가,중동,23,13,13,8.7,4.3,0,0,0,4.3,0,0,0,0,56.5
33,국가,인도,3,33.3,0,33.3,0,0,0,0,0,0,0,0,0,33.3
34,국가,필리핀,7,28.6,14.3,28.6,14.3,0,0,0,0,0,0,0,0,14.3
35,국가,인도네시아,7,28.6,28.6,0,0,0,0,0,0,0,0,0,0,42.9
36,국가,베트남,9,0,22.2,11.1,11.1,0,0,11.1,0,0,0,0,0,44.4
37,국가,몽골,10,0,30,20,10,0,10,10,0,0,0,10,0,10
38,국가,기타,136,19.9,11,10.3,3.7,8.8,1.5,0.7,2.9,2.9,0,0.7,0.7,36.8
39,성별,남성,576,23.3,9.4,10.2,3.6,4.2,1.6,1,1.9,0.5,1,1,0.3,41.8
40,성별,여성,822,17.9,15,12.2,4.3,3.6,1.5,1.6,1,1.5,0.5,0.4,0.4,40.4
41,연령,15-20 세,63,28.6,9.5,15.9,4.8,6.3,4.8,0,1.6,4.8,0,1.6,0,22.2
42,연령,21-30 세,389,22.9,11.8,12.1,4.6,4.9,2.3,1,1.3,1.8,0.3,0.8,0.3,36
43,연령,31-40 세,405,21,16.8,8.9,6.2,4,1.2,2,2.5,1,1,0.2,0.5,34.8
44,연령,41-50 세,201,19.4,13.4,11.9,4,0.5,0.5,2,0.5,0.5,1,1,0.5,44.8
45,연령,51-60 세,222,13.1,10.4,12.2,0.5,5,1.4,0.5,0.5,0,0.9,0.9,0,55
46,연령,61 세이상,118,17.8,5.9,12.7,0.8,2.5,0,1.7,0.8,0,0.8,0,0.8,55.9
47,방한목적,여가/위락/휴식,316,38.6,17.7,14.9,1.9,7.6,3.5,3.5,2.2,4.4,1.6,1.3,0,2.8
48,방한목적,친구/친지방문,1082,14.7,11.2,10.4,4.6,2.8,0.9,0.7,1.1,0.1,0.5,0.5,0.5,52.1
49,입국과정,자가격리포함,787,17.7,13.3,11.2,5,3.4,1.4,1.8,1.7,0.8,0.6,0.8,0.1,42.3
50,입국과정,자가격리미포함,611,23.2,11.8,11.6,2.8,4.4,1.6,0.8,1,1.5,0.8,0.5,0.7,39.3
51,방한횟수,1회,370,18.1,14.1,11.9,2.4,8.1,1.1,0.8,1.6,2.2,0.5,0.8,0,38.4
52,방한횟수,2회,241,24.1,8.7,9.5,3.3,2.5,1.2,2.1,1.2,1.2,0.8,1.7,0.8,42.7
53,방한횟수,3회,181,21,8.3,11.6,3.9,2.8,3.3,1.7,0.6,0.6,0.6,0.6,0,45.3
54,방한횟수,4회 이상,606,19.5,14.7,11.7,5.3,2.1,1.3,1.3,1.5,0.5,0.8,0.2,0.5,40.6

In [4]:
data_year = df2.iloc[14:18:,1:]
data_year

,통계분류(2),사례수,음식/미식탐방,쇼핑,자연 풍경 감상,패션 유행 등 세련된 현대 문화 체험,역사/문화유적/전통문화 체험,유흥/놀이 시설 체험,치료 및 미용 서비스 체험,여행 가능한 여가시간,K-POP/한류스타 관련 공연팬미팅촬영지 등 체험,레저 및 스포츠 활동,자국과의 이동거리,경제적인 여행비용,기타
14,1분기,261,20.3,15.7,11.9,6.9,3.4,0.8,1.1,2.3,0,0.8,0.4,0,36.4
15,2분기,252,19,9.9,14.7,9.1,2.4,1.2,3.2,0.4,0.4,0.4,0.4,0,38.9
16,3분기,338,13.3,12.4,8.9,0.9,3.8,1.5,1.5,0.6,0.3,0.3,0.6,0.3,55.6
17,4분기,547,24.7,12.6,11.2,2.2,4.8,2,0.5,1.8,2.4,1.1,0.9,0.7,35.1

In [5]:
data_year.rename(columns = {"통계분류(2)":"분기별"}, inplace=True)
data_year

,분기별,사례수,음식/미식탐방,쇼핑,자연 풍경 감상,패션 유행 등 세련된 현대 문화 체험,역사/문화유적/전통문화 체험,유흥/놀이 시설 체험,치료 및 미용 서비스 체험,여행 가능한 여가시간,K-POP/한류스타 관련 공연팬미팅촬영지 등 체험,레저 및 스포츠 활동,자국과의 이동거리,경제적인 여행비용,기타
14,1분기,261,20.3,15.7,11.9,6.9,3.4,0.8,1.1,2.3,0,0.8,0.4,0,36.4
15,2분기,252,19,9.9,14.7,9.1,2.4,1.2,3.2,0.4,0.4,0.4,0.4,0,38.9
16,3분기,338,13.3,12.4,8.9,0.9,3.8,1.5,1.5,0.6,0.3,0.3,0.6,0.3,55.6
17,4분기,547,24.7,12.6,11.2,2.2,4.8,2,0.5,1.8,2.4,1.1,0.9,0.7,35.1

In [6]:
data_year.columns[1:]

Index(['사례수', '음식/미식탐방', '쇼핑', '자연 풍경 감상', '패션 유행 등 세련된 현대 문화 체험',
       '역사/문화유적/전통문화 체험', '유흥/놀이 시설 체험', '치료 및 미용 서비스 체험', '여행 가능한 여가시간',
       'K-POP/한류스타 관련 공연팬미팅촬영지 등 체험', '레저 및 스포츠 활동', '자국과의 이동거리', '경제적인 여행비용',
       '기타'],
      dtype='object')

In [7]:
data_year.dtypes

분기별                            object
사례수                            object
음식/미식탐방                        object
쇼핑                             object
자연 풍경 감상                       object
패션 유행 등 세련된 현대 문화 체험           object
역사/문화유적/전통문화 체험                object
유흥/놀이 시설 체험                    object
치료 및 미용 서비스 체험                 object
여행 가능한 여가시간                    object
K-POP/한류스타 관련 공연팬미팅촬영지 등 체험    object
레저 및 스포츠 활동                    object
자국과의 이동거리                      object
경제적인 여행비용                      object
기타                             object
dtype: object

In [8]:
data_year.set_index('분기별',inplace=True)
data_year = data_year.astype('float')   
data_year.reset_index(inplace=True)
data_year

,분기별,사례수,음식/미식탐방,쇼핑,자연 풍경 감상,패션 유행 등 세련된 현대 문화 체험,역사/문화유적/전통문화 체험,유흥/놀이 시설 체험,치료 및 미용 서비스 체험,여행 가능한 여가시간,K-POP/한류스타 관련 공연팬미팅촬영지 등 체험,레저 및 스포츠 활동,자국과의 이동거리,경제적인 여행비용,기타
0,1분기,261.0,20.3,15.7,11.9,6.9,3.4,0.8,1.1,2.3,0.0,0.8,0.4,0.0,36.4
1,2분기,252.0,19.0,9.9,14.7,9.1,2.4,1.2,3.2,0.4,0.4,0.4,0.4,0.0,38.9
2,3분기,338.0,13.3,12.4,8.9,0.9,3.8,1.5,1.5,0.6,0.3,0.3,0.6,0.3,55.6
3,4분기,547.0,24.7,12.6,11.2,2.2,4.8,2.0,0.5,1.8,2.4,1.1,0.9,0.7,35.1

In [13]:
data_year_copy = data_year.copy()
data_year_copy['음식/미식탐방'] = data_year_copy['사례수']*data_year_copy['음식/미식탐방']/100
data_year_copy['쇼핑'] = data_year_copy['사례수']*data_year_copy['쇼핑']/100
data_year_copy['자연 풍경 감상'] = data_year_copy['사례수']*data_year_copy['자연 풍경 감상']/100
data_year_copy['패션 유행 등 세련된 현대 문화 체험'] = data_year_copy['사례수']*data_year_copy['패션 유행 등 세련된 현대 문화 체험']/100
data_year_copy['역사/문화유적/전통문화 체험'] = data_year_copy['사례수']*data_year_copy['역사/문화유적/전통문화 체험']/100
data_year_copy['유흥/놀이 시설 체험'] = data_year_copy['사례수']*data_year_copy['유흥/놀이 시설 체험']/100
data_year_copy['치료 및 미용 서비스 체험'] = data_year_copy['사례수']*data_year_copy['치료 및 미용 서비스 체험']/100
data_year_copy['여행 가능한 여가시간'] = data_year_copy['사례수']*data_year_copy['여행 가능한 여가시간']/100
data_year_copy['K-POP/한류스타 관련 공연팬미팅촬영지 등 체험'] = data_year_copy['사례수']*data_year_copy['K-POP/한류스타 관련 공연팬미팅촬영지 등 체험']/100
data_year_copy['레저 및 스포츠 활동'] = data_year_copy['사례수']*data_year_copy['레저 및 스포츠 활동']/100
data_year_copy['자국과의 이동거리'] = data_year_copy['사례수']*data_year_copy['자국과의 이동거리']/100
data_year_copy['경제적인 여행비용'] = data_year_copy['사례수']*data_year_copy['경제적인 여행비용']/100
data_year_copy['기타'] = data_year_copy['사례수']*data_year_copy['기타']/100
data_year_copy

,분기별,사례수,음식/미식탐방,쇼핑,자연 풍경 감상,패션 유행 등 세련된 현대 문화 체험,역사/문화유적/전통문화 체험,유흥/놀이 시설 체험,치료 및 미용 서비스 체험,여행 가능한 여가시간,K-POP/한류스타 관련 공연팬미팅촬영지 등 체험,레저 및 스포츠 활동,자국과의 이동거리,경제적인 여행비용,기타
0,1분기,261.0,52.983,40.977,31.059,18.009,8.874,2.088,2.871,6.003,0.000,2.088,1.044,0.000,95.004
1,2분기,252.0,47.880,24.948,37.044,22.932,6.048,3.024,8.064,1.008,1.008,1.008,1.008,0.000,98.028
2,3분기,338.0,44.954,41.912,30.082,3.042,12.844,5.070,5.070,2.028,1.014,1.014,2.028,1.014,187.928
3,4분기,547.0,135.109,68.922,61.264,12.034,26.256,10.940,2.735,9.846,13.128,6.017,4.923,3.829,191.997

In [14]:
data_year_copy.iloc[::,1:].astype(int)

,사례수,음식/미식탐방,쇼핑,자연 풍경 감상,패션 유행 등 세련된 현대 문화 체험,역사/문화유적/전통문화 체험,유흥/놀이 시설 체험,치료 및 미용 서비스 체험,여행 가능한 여가시간,K-POP/한류스타 관련 공연팬미팅촬영지 등 체험,레저 및 스포츠 활동,자국과의 이동거리,경제적인 여행비용,기타
0,261,52,40,31,18,8,2,2,6,0,2,1,0,95
1,252,47,24,37,22,6,3,8,1,1,1,1,0,98
2,338,44,41,30,3,12,5,5,2,1,1,2,1,187
3,547,135,68,61,12,26,10,2,9,13,6,4,3,191

In [15]:
data_year_copy.set_index('분기별',inplace=True)
data_year_copy = data_year_copy.astype('int')   #inplace 가 없음
data_year_copy.reset_index(inplace=True)
data_year_copy

,분기별,사례수,음식/미식탐방,쇼핑,자연 풍경 감상,패션 유행 등 세련된 현대 문화 체험,역사/문화유적/전통문화 체험,유흥/놀이 시설 체험,치료 및 미용 서비스 체험,여행 가능한 여가시간,K-POP/한류스타 관련 공연팬미팅촬영지 등 체험,레저 및 스포츠 활동,자국과의 이동거리,경제적인 여행비용,기타
0,1분기,261,52,40,31,18,8,2,2,6,0,2,1,0,95
1,2분기,252,47,24,37,22,6,3,8,1,1,1,1,0,98
2,3분기,338,44,41,30,3,12,5,5,2,1,1,2,1,187
3,4분기,547,135,68,61,12,26,10,2,9,13,6,4,3,191